config/routes.rb
Railsblog::Application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  match 'tags/:name' => 'Tags#show', :as => 'tag'

  match 'posts/:name' => 'Posts#show', :as => 'post'

  match 'posts' => 'Posts#index', :as => 'posts'

  match 'posts/:name/comments/new' => 'Comments#create', :as => 'new_comment'

  match 'pages/:name' => 'Pages#show', :as => 'page'

  root :to => 'Posts#index'

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data
	
	def url_thumb
	  @url_thumb ||= begin
	    extname = File.extname(filename).gsub(/^\./, '')
      "/javascripts/ckeditor/filebrowser/images/thumbs/#{extname}.gif"
	  end
	end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
	                  :styles => { :content => '800>', :thumb => '118x100#' }
	
	validates_attachment_size :data, :less_than => 2.megabytes
	validates_attachment_presence :data
	
	def url_content
	  url(:content)
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    
    validates :commenter, :presence => true
    validates :email,     :format   => { :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i , :message => 'Only email address allowed' },
                          :presence => true
    validates :website,   :format   => { :with => /((http|https):\/\/|[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)+.*)$/ , :message => 'Only url allowed'}

    validates :body,      :presence => true

    belongs_to :post


end

app/models/page.rb
class Page < ActiveRecord::Base
    validates :title, :presence    => true,
                      :length      => {:minimum => 5}

    validates :name,  :presence    => true, 
                      :length      => {:minimum => 5},
                      :uniqueness  => true,
                      :format      => {:with => /^[-_a-zA-Z0-9]+$/, :message => 'Only letters and digits allowed'}


end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :title, :presence    => true,
                      :length      => {:minimum => 5}

    validates :name,  :presence    => true, 
                      :length      => {:minimum => 5},
                      :uniqueness  => true,
                      :format      => {:with => /^[-_a-zA-Z0-9]+$/, :message => 'Only letters and digits allowed'}
    
    validates :content, :presence  => true

    acts_as_taggable
    acts_as_taggable_on :category

    has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
         @post = Post.find_by_name_and_published(params[:name], true)
         if @post.commentable
            @comment = @post.comments.create(params[:comment])

            if @comment.valid?
                redirect_to post_path(@post.name), :notice=> 'Submitted, thank you.'
            else
                render 'posts/show'
            end
         else
            redirect_to post_path(@post.name), :notice=> 'Not allowed to comment'

         end

    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def show
        @page = Page.find_by_name(params[:name])
    end
end

app/controllers/posts_controller.rb
require 'digest/md5'

class PostsController < ApplicationController

    def index
        @posts = Post.where(:published=>true).order('created_at DESC').paginate(:page=>params[:page], :per_page => 2) 

        respond_to do |format|
            format.html {}

            format.rss do
                @posts = Post.where(:published=>true).all(:order => "created_at DESC", :limit => 20)
                render :layout=>false
            end if params[:format] == 'rss'
        end
    end

    def show
        @post = Post.find_by_name_and_published(params[:name], true)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    def show 
        @posts = Post.where(:published=>true).tagged_with(params[:name]).paginate(:page=>params[:page], :per_page => 2) 

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/comments/_comment.html.erb
<% if comment.id %>
<dl class="comment">
	<dt>
        <img src="http://www.gravatar.com/avatar/<%=Digest::MD5.hexdigest(comment.email.downcase)%>?s=48" width="48" height="48" />
    </dt>
	<dd>
    <span>    <%= link_to comment.commenter, comment.website %> : </span>
    <p><%= comment.body %></p>
    </dd>
</dl>
<% end %>

app/views/comments/_form.html.erb
<section id="create_form">
<%= notice %>
<%= form_for(Comment.new, :url => new_comment_url(@post.name), :method => 'post' ) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %><em><%=h @comment.errors[:commenter] if @comment %></em>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %><em><%=h @comment.errors[:website] if @comment %></em>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %><em><%=h @comment.errors[:email] if @comment %></em>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
    <em><%=h @comment.errors[:body] if @comment %></em>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</section>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 9]><html class="ie"><![endif]-->
<!--[if gte IE 9]><!--><html><!--<![endif]-->

	
	<head>
		<meta charset="utf-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
		<title>Lux et veritas</title>
		
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<link rel="alternate" type="application/rss+xml"href="http://blog.keekun.com/posts.rss" title="Lux et veritas">
        <%= auto_discovery_link_tag(:rss, "http://blog.keekun.com") %>
        <%= stylesheet_link_tag    "application" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>
		
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
	</head>
	
	<body>
		<header>
			<div class="wrapper">
				<h1><a href="/">Lux et veritas</a></h1>
				<h2>#Mathematics,Science & Aesthetics   #<%= link_to 'About', page_url('chifung_cheung')%> #<a href="/posts.rss">RSS</a></h2>
			</div>
		</header>
        <section>
        <figure class="stripes" id="fig1""></figure>
        </section>
		
		
        <%= yield %>

        <footer>
        <figure class="stripes"> </figure>
        <section class="twoway" id="footer">
        <article class="wrapper">
        <h4>About this site</h4>
        <p>This site,its design and code are developed by <%= link_to 'Cheung Chifung', page_url('chifung_cheung')%> and powered by <a href="http://rubyonrails.org/" target="_blank">Rails 3.1</a>. All rights reserved. </p>
        </article>
        <article class="wrapper">
        <h4>About me</h4>
        <p><a href="http://www.twitter.com/kee_kun" target="_blank">@Kee_Kun</a></p>
        <p>Male,from Canton Province,China.Studying in Japan(Engineering Management Graduate Program). </p>
        </article>
        </section>
        </footer>
	</body>
	
</html>

app/views/pages/show.html.erb
<article class="twoway wrapper">
<h3><%= @page.title%></h3>
<section id="article_page" class="article_preview">
<p><%= @page.content.html_safe %></p>
</section>
</article>

app/views/posts/index.html.erb
<section class="wrapper twoway">
    <% if @posts.size > 0 %>
      <% @posts.each do |post| %>
        <article class="wrapper article_preview">
            <h3> <%= link_to post.title, post_url(post.name) %> </h3>
            <p>
                <% if post.preview == nil or post.preview == '' %>
               <%= post.content.html_safe %> 
                <% else %>
               <%= post.preview.html_safe %> 
               <br/>
                <%= link_to 'Read more..', post_url(post.name) %>
            <% end %>
            </p>
            <p>
            <section class="article_detail"><span>Comments(<%=post.comments.size%>)</span> @ <time datetime="<%=post.created_at.to_s(:rfc822)%>"><%=post.created_at.strftime('%b %d, %Y')%></time></section>
            </p>
        </article>
      <% end %>
    <% else %>
    <% end %>
    <footer>
        <%= will_paginate @posts %>
    </footer>
</section>

app/views/posts/show.html.erb
<article class="twoway wrapper">
<h3><%= @post.title%></h3>
<section class="article_detail">
<span>Tags:</span>
<% @post.tags.each do |category|%>
<%= link_to category.name,tag_url(category.name) %>
<% end %> / 
<span>Comments(<%=@post.comments.size%>)</span> / 
<time datetime="<%=@post.created_at.to_s(:rfc822)%>"><%=@post.created_at.strftime('%b %d, %Y')%></time>
</section>
<section id="article_content" class="article_preview">
<p><%= @post.content.html_safe %></p>
</section>
<% if @post.find_related_tags.length > 0 %>
<section id="releated_articles">
    <h4>Releted Articles</h4>
    <ul>
    <% @post.find_related_tags.each do |releated_post| %>
    <li><%= link_to releated_post.title, post_url(releated_post.name) %></li>
    <% end %>
    </ul>
</section>
<% end %>
<%= render @post.comments %>
<% if @post.commentable %>
<%= render 'comments/form' %>
<% end %>
<br/>
</article>

app/views/tags/show.html.erb
<section class="wrapper twoway">
    <% if @posts.size > 0 %>
      <% @posts.each do |post| %>
        <article class="wrapper article_preview">
            <h3> <%= link_to post.title, post_url(post.name) %> </h3>
            <p>
                <% if post.preview == nil or post.preview == '' %>
               <%= post.content.html_safe %> 
                <% else %>
               <%= post.preview.html_safe %> 
               <br/>
                <%= link_to 'Read more..', post_url(post.name) %>
                <% end %>
            </p>
            <p>
            <section class="article_detail"><span>Comments(<%=post.comments.size%>)</span> @ <time datetime="<%=post.created_at.to_s(:rfc822)%>"><%=post.created_at.strftime('%b %d, %Y')%></time></section>
            </p>
        </article>
      <% end %>
    <% else %>
    <% end %>
    <footer>
        <%= will_paginate @posts %>
    </footer>
</section>